language: node_js
node_js:
- 0.12.7
branches:
  only:
    - master
before_install:
- openssl enc -aes-256-cbc -d -in travis_deploy/deploy_key.enc -out travis_deploy/deploy_key -K $encrypted_key -iv $encrypted_iv -pass pass:$encrypted_pass
script: ./travis_deploy/deploy.sh 
