language: node_js
node_js:
- 0.12.7
before_install:
- openssl aes-256-cbc -K $encrypted_e40f925ea466_key -iv $encrypted_e40f925ea466_iv
  -in travis_deploy/deploy_key.enc -out travis_deploy/deploy_key -d
script: ./travis_deploy/deploy.sh