---
- hosts: all
  tasks:
    - name: Update repo
      shell: "cd /opt/vegosvar && su vegosvar -c 'cd /opt/vegosvar && git pull && npm install && gulp prod'"

    - name: Copy config
      copy: src=../config.js dest=/opt/vegosvar/config.js owner=vegosvar group=vegosvar mode=0644

    - name: Restart service
      service: name=vegosvar state=restarted